SELECT id AS 'TREE.ID', ty AS 'TYPE'
FROM (
    SELECT t1.ID as id, 'INNER' as ty FROM TREE t1
    RIGHT JOIN TREE t2 ON t1.ID = t2.P_ID
    WHERE t1.P_ID IS NOT NULL
    UNION
    SELECT ID AS id, 'ROOT' AS ty FROM TREE WHERE P_ID IS NULL
    UNION
    SELECT t1.ID AS id, 'LEAF' as ty FROM TREE t1
    LEFT JOIN TREE t2 ON t1.ID = t2.P_ID
    WHERE t2.ID IS NULL
) as res
ORDER BY id ASC